spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://127.0.0.1:5432/example-microservice
    initialization-mode: always
    driver-class-name: org.postgresql.Driver